openapi: 3.0.0
info:
  title: API Utilisateurs
  version: 1.0.0

paths:
  /users:
    get:
      summary: Récupérer tous les utilisateurs
      responses:
        '200':
          description: Liste des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Alice"
                    email:
                      type: string
                      format: email
                      example: "alice@example.com"
