openapi: 3.0.3
info:
  title: API Utilisateurs
  version: 1.0.0
  description: API simple pour gérer les utilisateurs.
paths:
  /users:
    get:
      summary: Récupère une liste d’utilisateurs
      description: Retourne une liste paginée d’utilisateurs.
      parameters:
        - name: page
          in: query
          description: Numéro de la page à récupérer
          required: false
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          description: Nombre d’utilisateurs par page
          required: false
          schema:
            type: integer
            example: 20
      responses:
        '200':
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad types for provided query parameters

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Alice
        email:
          type: string
          format: email
          example: alice@example.com
